# Generated by Django 5.2.3 on 2025-06-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
